type UniformFunction =
  | WebGLRenderingContext["uniform1f"]
  | WebGLRenderingContext["uniform2f"]
  | WebGLRenderingContext["uniform3f"]
  | WebGLRenderingContext["uniform4f"]
  | WebGLRenderingContext["uniform1fv"]
  | WebGLRenderingContext["uniform2fv"]
  | WebGLRenderingContext["uniform3fv"]
  | WebGLRenderingContext["uniform4fv"]
  | WebGLRenderingContext["uniform1i"]
  | WebGLRenderingContext["uniform2i"]
  | WebGLRenderingContext["uniform3i"]
  | WebGLRenderingContext["uniform4i"]
  | WebGLRenderingContext["uniform1iv"]
  | WebGLRenderingContext["uniform2iv"]
  | WebGLRenderingContext["uniform3iv"]
  | WebGLRenderingContext["uniform4iv"]
  | WebGLRenderingContext["uniformMatrix2fv"]
  | WebGLRenderingContext["uniformMatrix3fv"]
  | WebGLRenderingContext["uniformMatrix4fv"];
export default UniformFunction;
